# Generated by Django 5.2.17 on 2026-08-29 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=256)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtpAuthorization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='authorization', to='otp.otpchallenge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpRateLimitBucket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('TARGET', 'Target'), ('ACCOUNT', 'Account'), ('SOURCE', 'Request source')], max_length=16)),
                ('key_hash', models.CharField(max_length=64)),
                ('window_started_at', models.DateTimeField()),
                ('request_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'key_hash'), name='otp_unique_rate_limit_bucket')],
            },
        ),
        migrations.CreateModel(
            name='OtpTargetState',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email verification'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGE', 'Password change'), ('EMAIL_CHANGE', 'Email change'), ('PHONE_VERIFICATION', 'Phone verification')], max_length=32)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], max_length=16)),
                ('target_hash', models.CharField(max_length=64)),
                ('last_issued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('purpose', 'channel', 'target_hash'), name='otp_unique_target_purpose_channel')],
            },
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='otp.otptargetstate'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['state', '-created_at'], name='otp_otpchal_state_i_7cc438_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('invalidated_at__isnull', True), ('locked_at__isnull', True)), fields=('state',), name='otp_one_unfinished_challenge_per_target'),
        ),
    ]
