# Generated by Django 5.2.17 on 2026-08-08 22:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_medicaldocument_processing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentText',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True)),
                ('page_count', models.PositiveIntegerField()),
                ('character_count', models.PositiveIntegerField()),
                ('meaningful_character_count', models.PositiveIntegerField()),
                ('usable', models.BooleanField()),
                ('usability_reason', models.CharField(max_length=64)),
                ('has_pages_requiring_ocr', models.BooleanField(default=False)),
                ('extraction_method', models.CharField(choices=[('PDF_TEXT', 'PDF text')], max_length=16)),
                ('extractor_name', models.CharField(max_length=64)),
                ('extractor_version', models.CharField(max_length=32)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='document_text', to='documents.medicaldocument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentTextPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('meaningful_character_count', models.PositiveIntegerField()),
                ('requires_ocr', models.BooleanField(default=False)),
                ('document_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='processing.documenttext')),
            ],
            options={
                'ordering': ('page_number',),
                'constraints': [models.UniqueConstraint(fields=('document_text', 'page_number'), name='processing_unique_document_text_page'), models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='processing_page_number_positive')],
            },
        ),
    ]
