# Generated by Django 5.2.17 on 2026-08-09 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_medicaldocument_processing_status_and_more'),
        ('processing', '0002_m8_ocr_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCandidate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_date', models.DateField()),
                ('alternative_date', models.DateField(blank=True, null=True)),
                ('raw_value', models.CharField(max_length=64)),
                ('normalized_value', models.CharField(max_length=64)),
                ('candidate_type', models.CharField(choices=[('REPORT_DATE', 'Report date'), ('RESULT_DATE', 'Result date'), ('ISSUE_DATE', 'Issue date'), ('COLLECTION_DATE', 'Collection date'), ('SAMPLE_DATE', 'Sample date'), ('EXAMINATION_DATE', 'Examination date'), ('ADMISSION_DATE', 'Admission date'), ('DISCHARGE_DATE', 'Discharge date'), ('PRINT_DATE', 'Print date'), ('DATE_OF_BIRTH', 'Date of birth'), ('UNKNOWN', 'Unknown')], max_length=24)),
                ('score', models.FloatField()),
                ('page_number', models.PositiveIntegerField()),
                ('context', models.CharField(max_length=256)),
                ('source', models.CharField(choices=[('PDF_TEXT', 'PDF text'), ('OCR', 'OCR')], max_length=16)),
                ('occurrence_index', models.PositiveIntegerField()),
                ('ambiguous', models.BooleanField(default=False)),
                ('parsing_rule', models.CharField(max_length=32)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('is_suggested', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='date_candidates', to='documents.medicaldocument')),
            ],
            options={
                'ordering': ('-score', 'page_number', 'occurrence_index', 'uuid'),
                'indexes': [models.Index(fields=['document', 'pipeline_version'], name='date_candidate_pipeline_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'pipeline_version', 'page_number', 'occurrence_index', 'candidate_type'), name='date_candidate_occurrence_unique'), models.UniqueConstraint(condition=models.Q(('is_suggested', True)), fields=('document',), name='date_candidate_one_suggested'), models.CheckConstraint(condition=models.Q(('score__gte', 0.0), ('score__lte', 1.0)), name='date_candidate_score_range'), models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='date_candidate_page_positive')],
            },
        ),
    ]
