# Generated by Django 5.2.17 on 2026-08-09 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_medicaldocument_processing_status_and_more'),
        ('processing', '0003_datecandidate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datecandidate',
            name='date_candidate_occurrence_unique',
        ),
        migrations.RemoveConstraint(
            model_name='datecandidate',
            name='date_candidate_one_suggested',
        ),
        migrations.RemoveIndex(
            model_name='datecandidate',
            name='date_candidate_pipeline_idx',
        ),
        migrations.AddField(
            model_name='datecandidate',
            name='candidate_set_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='datecandidate',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='datecandidate',
            index=models.Index(fields=['document', 'is_current', 'pipeline_version'], name='date_candidate_pipeline_idx'),
        ),
        migrations.AddConstraint(
            model_name='datecandidate',
            constraint=models.UniqueConstraint(fields=('document', 'candidate_set_uuid', 'pipeline_version', 'page_number', 'occurrence_index', 'candidate_type'), name='date_candidate_occurrence_unique'),
        ),
        migrations.AddConstraint(
            model_name='datecandidate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True), ('is_suggested', True)), fields=('document',), name='date_candidate_one_suggested'),
        ),
    ]
