# Generated by Django 5.2.17 on 2026-08-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_remove_datecandidate_date_candidate_occurrence_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datecandidate',
            name='candidate_type',
            field=models.CharField(choices=[('REPORT_DATE', 'Report date'), ('RESULT_DATE', 'Result date'), ('ISSUE_DATE', 'Issue date'), ('COLLECTION_DATE', 'Collection date'), ('SAMPLE_DATE', 'Sample date'), ('EXAMINATION_DATE', 'Examination date'), ('ADMISSION_DATE', 'Admission date'), ('DISCHARGE_DATE', 'Discharge date'), ('APPLICATION_DATE', 'Application date'), ('PRINT_DATE', 'Print date'), ('DATE_OF_BIRTH', 'Date of birth'), ('UNKNOWN', 'Unknown')], max_length=24),
        ),
    ]
