# Generated by Django 5.2.17 on 2026-08-18 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_alter_datecandidate_candidate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTextSpan',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('confidence', models.FloatField()),
                ('x_min', models.FloatField()),
                ('y_min', models.FloatField()),
                ('x_max', models.FloatField()),
                ('y_max', models.FloatField()),
                ('source', models.CharField(choices=[('OCR', 'OCR'), ('PDF_TEXT', 'PDF text')], default='OCR', max_length=16)),
                ('page_width', models.PositiveIntegerField()),
                ('page_height', models.PositiveIntegerField()),
                ('document_text_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='processing.documenttextpage')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('document_text_page', 'sequence'), name='processing_unique_document_text_span_sequence'), models.CheckConstraint(condition=models.Q(('x_min__gte', 0.0), ('y_min__gte', 0.0), ('x_max__lte', 1.0), ('y_max__lte', 1.0), ('x_min__lte', models.F('x_max')), ('y_min__lte', models.F('y_max'))), name='processing_span_normalized_bounds'), models.CheckConstraint(condition=models.Q(('sequence__gte', 0)), name='processing_span_sequence_nonnegative')],
            },
        ),
    ]
