# Generated by Django 5.2.17 on 2026-08-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_medicaldocument_processing_status_and_more'),
        ('processing', '0006_documenttextspan'),
    ]

    operations = [
        migrations.AddField(
            model_name='datecandidate',
            name='page_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_candidates', to='documents.medicaldocumentpage'),
        ),
    ]
