# Generated by Django 5.2.17 on 2026-08-09 13:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('normalized_name', 'uuid'),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Use ISO alpha-2 code.')])),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(editable=False, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='facilities.administrativeregion')),
            ],
            options={
                'ordering': ('normalized_name', 'uuid'),
            },
        ),
        migrations.AddField(
            model_name='administrativeregion',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='facilities.country'),
        ),
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(editable=False, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('LABORATORY', 'Laboratory'), ('RADIOLOGY_CENTER', 'Radiology center'), ('PHARMACY', 'Pharmacy'), ('PRIMARY_CARE_CENTER', 'Primary care center'), ('SPECIALIZED_CENTER', 'Specialized center'), ('UNIVERSITY_HOSPITAL', 'University hospital'), ('OTHER', 'Other')], max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.administrativeregion')),
            ],
            options={
                'ordering': ('normalized_name', 'uuid'),
            },
        ),
        migrations.CreateModel(
            name='HealthcareFacilityAlias',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(editable=False, max_length=255)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='facilities.healthcarefacility')),
            ],
            options={
                'ordering': ('normalized_name', 'uuid'),
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('region', 'normalized_name'), name='facility_city_region_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='administrativeregion',
            constraint=models.UniqueConstraint(fields=('country', 'normalized_name'), name='facility_region_country_name_unique'),
        ),
        migrations.AddIndex(
            model_name='healthcarefacility',
            index=models.Index(fields=['active', 'normalized_name'], name='facility_active_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthcarefacility',
            constraint=models.CheckConstraint(condition=models.Q(('city__isnull', True), ('region__isnull', False), _connector='OR'), name='facility_city_requires_region'),
        ),
        migrations.AddConstraint(
            model_name='healthcarefacility',
            constraint=models.UniqueConstraint(fields=('country', 'city', 'normalized_name'), name='facility_country_city_name_unique', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='healthcarefacilityalias',
            constraint=models.UniqueConstraint(fields=('facility', 'normalized_name'), name='facility_alias_name_unique'),
        ),
    ]
