# Generated by Django 5.2.17 on 2026-08-08 19:29

import django.db.models.deletion
import identities.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=identities.storage.PrivateIdentityStorage(), upload_to='')),
                ('original_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=16)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('UNIFIED_NATIONAL_CARD', 'Unified National Card'), ('PASSPORT', 'Passport'), ('BIRTH_DOCUMENT', 'Birth document'), ('OTHER_GOVERNMENT_ID', 'Other government ID')], max_length=32)),
                ('document_number', models.CharField(max_length=128)),
                ('national_number', models.CharField(blank=True, max_length=128)),
                ('family_number', models.CharField(blank=True, max_length=128)),
                ('issuing_country', models.CharField(max_length=2)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('EXPIRED', 'Expired'), ('REPLACED', 'Replaced'), ('REVOKED', 'Revoked')], default='CURRENT', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='patients.patientprofile')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_attempts', to='identities.identitydocument')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('back_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='back_for_documents', to='identities.identityfile')),
                ('front_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='front_for_documents', to='identities.identityfile')),
            ],
            options={
                'ordering': ('-created_at', '-uuid'),
            },
        ),
        migrations.CreateModel(
            name='IdentityDocumentEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('IDENTITY_DOCUMENT_UPLOADED', 'Identity document uploaded'), ('IDENTITY_DOCUMENT_REPLACEMENT_SUBMITTED', 'Identity document replacement submitted'), ('IDENTITY_VERIFIED', 'Identity verified'), ('IDENTITY_REJECTED', 'Identity rejected'), ('IDENTITY_DOCUMENT_REPLACED', 'Identity document replaced')], max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_document_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='identities.identitydocument')),
            ],
            options={
                'ordering': ('created_at', 'uuid'),
            },
        ),
        migrations.AddIndex(
            model_name='identitydocument',
            index=models.Index(fields=['verification_status', 'created_at'], name='identity_verify_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='identitydocument',
            index=models.Index(fields=['patient', 'document_type', 'status'], name='identity_patient_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='identitydocument',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CURRENT'), ('verification_status', 'VERIFIED')), fields=('patient', 'document_type'), name='identity_one_verified_current_type'),
        ),
        migrations.AddConstraint(
            model_name='identitydocument',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__isnull', True), ('issue_date__isnull', True), ('expiry_date__gt', models.F('issue_date')), _connector='OR'), name='identity_expiry_after_issue'),
        ),
    ]
