# Generated by Django 5.2.17 on 2026-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0002_identityextractionjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityextractionjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FINALIZED', 'Finalized'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=16),
        ),
    ]
