# Generated by Django 5.2.17 on 2026-08-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0003_alter_identityextractionjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='unique_card_body_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
