# Generated by Django 5.2.17 on 2026-08-27 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0004_identitydocument_unique_card_body_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='review_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_blood_group',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_document_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_family_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_father_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_given_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_grandfather_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_mother_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_national_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_nationality',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_sex',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='reviewed_unique_card_body_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='identitydocumentevent',
            name='event_type',
            field=models.CharField(choices=[('IDENTITY_DOCUMENT_UPLOADED', 'Identity document uploaded'), ('IDENTITY_DOCUMENT_REPLACEMENT_SUBMITTED', 'Identity document replacement submitted'), ('IDENTITY_VERIFIED', 'Identity verified'), ('IDENTITY_REJECTED', 'Identity rejected'), ('IDENTITY_DOCUMENT_REPLACED', 'Identity document replaced'), ('IDENTITY_REVIEW_FIELDS_CORRECTED', 'Identity review fields corrected'), ('IDENTITY_VERIFIED_FIELDS_CORRECTED', 'Identity verified fields corrected')], max_length=48),
        ),
        migrations.CreateModel(
            name='IdentityFieldCorrection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=64)),
                ('original_value', models.TextField(blank=True, default='')),
                ('reviewed_value', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('REVIEWER_CORRECTION', 'Reviewer correction'), ('VERIFIED_CORRECTION', 'Verified correction')], default='REVIEWER_CORRECTION', max_length=32)),
                ('review_version', models.PositiveIntegerField(default=0)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('reason_category', models.CharField(blank=True, choices=[('OCR_CORRECTION', 'OCR correction discovered after verification'), ('DATA_ENTRY', 'Data-entry correction'), ('UPDATED_DOCUMENT', 'Updated authoritative identity document'), ('ADMINISTRATIVE', 'Administrative correction'), ('OTHER', 'Other')], default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_field_corrections', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_corrections', to='identities.identitydocument')),
            ],
            options={
                'ordering': ('created_at', 'uuid'),
                'indexes': [models.Index(fields=['document', 'field'], name='idcorr_doc_field_idx')],
            },
        ),
    ]
