# Generated by Django 5.2.17 on 2026-08-08 20:42

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccountClaim',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_email', models.EmailField(max_length=254)),
                ('requested_phone', models.CharField(max_length=32)),
                ('submitted_name', models.CharField(max_length=255)),
                ('submitted_date_of_birth', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('MORE_INFORMATION_REQUIRED', 'More information required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('name_comparison', models.CharField(choices=[('MATCH', 'Match'), ('MISMATCH', 'Mismatch'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=16)),
                ('date_of_birth_comparison', models.CharField(choices=[('MATCH', 'Match'), ('MISMATCH', 'Mismatch'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=16)),
                ('document_number_comparison', models.CharField(choices=[('MATCH', 'Match'), ('MISMATCH', 'Mismatch'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('approved_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_account_claim', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_claims', to='patients.patientprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_claims_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'uuid'),
            },
        ),
        migrations.CreateModel(
            name='ClaimIdentityEvidence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('UNIFIED_NATIONAL_CARD', 'Unified National Card'), ('PASSPORT', 'Passport')], max_length=32)),
                ('document_number', models.CharField(max_length=128)),
                ('issuing_country', models.CharField(default='IQ', max_length=2)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('back_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_back_evidence', to='identities.identityfile')),
                ('front_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_front_evidence', to='identities.identityfile')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_evidence', to='claims.patientaccountclaim')),
            ],
        ),
        migrations.CreateModel(
            name='AccountActivation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='claim_activation', to=settings.AUTH_USER_MODEL)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activation', to='claims.patientaccountclaim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientAccountClaimEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CLAIM_SUBMITTED', 'Claim submitted'), ('CLAIM_UNDER_REVIEW', 'Claim under review'), ('CLAIM_MORE_INFORMATION_REQUIRED', 'More information required'), ('CLAIM_APPROVED', 'Claim approved'), ('PATIENT_ACCOUNT_LINKED', 'Patient account linked'), ('ACCOUNT_ACTIVATION_CREATED', 'Activation created'), ('CLAIM_REJECTED', 'Claim rejected'), ('CLAIM_ACCOUNT_ACTIVATED', 'Account activated')], max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_claim_events', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='claims.patientaccountclaim')),
            ],
            options={
                'ordering': ('created_at', 'uuid'),
            },
        ),
        migrations.AddConstraint(
            model_name='patientaccountclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'UNDER_REVIEW', 'MORE_INFORMATION_REQUIRED'))), fields=('patient',), name='claim_one_active_per_patient'),
        ),
        migrations.AddConstraint(
            model_name='patientaccountclaim',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('requested_email'), condition=models.Q(('status__in', ('PENDING', 'UNDER_REVIEW', 'MORE_INFORMATION_REQUIRED'))), name='claim_one_active_per_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='claimidentityevidence',
            constraint=models.UniqueConstraint(fields=('claim', 'document_type'), name='claim_one_evidence_type'),
        ),
    ]
