# Generated by Django 5.2.17 on 2026-08-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accounts_user_email_ci_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_ACTIVATION', 'Pending activation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled')], default='PENDING', max_length=24),
        ),
    ]
