# Generated by Django 5.2.17 on 2026-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_email_verified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_session_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
