# Generated by Django 5.2.17 on 2026-08-08 19:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('LEGAL_GUARDIAN', 'Legal guardian')], max_length=24)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('family_number_result', models.CharField(choices=[('MATCH', 'Match'), ('MISMATCH', 'Mismatch'), ('UNAVAILABLE', 'Unavailable')], default='UNAVAILABLE', max_length=16)),
                ('active', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, choices=[('PATIENT_REACHED_ADULTHOOD', 'Patient reached adulthood'), ('REVOKED', 'Revoked'), ('RELATIONSHIP_INVALIDATED', 'Relationship invalidated'), ('ADMINISTRATIVE_CORRECTION', 'Administrative correction'), ('OTHER', 'Other')], max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('guardian_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_relationships', to=settings.AUTH_USER_MODEL)),
                ('minor_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_relationships', to='patients.patientprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardian_relationships_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-uuid'),
            },
        ),
        migrations.CreateModel(
            name='GuardianEvidence',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('LEGAL_GUARDIANSHIP_DOCUMENT', 'Legal guardianship document'), ('COURT_DOCUMENT', 'Court document'), ('OTHER_OFFICIAL_EVIDENCE', 'Other official evidence')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardian_evidences', to='identities.identityfile')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='guardians.guardianrelationship')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuardianRelationshipEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('MINOR_CREATED', 'Minor created'), ('GUARDIAN_RELATIONSHIP_SUBMITTED', 'Relationship submitted'), ('MINOR_IDENTITY_DOCUMENT_SUBMITTED', 'Minor identity document submitted'), ('FAMILY_NUMBER_MATCHED', 'Family number matched'), ('FAMILY_NUMBER_MISMATCHED', 'Family number mismatched'), ('GUARDIAN_RELATIONSHIP_VERIFIED', 'Relationship verified'), ('GUARDIAN_RELATIONSHIP_REJECTED', 'Relationship rejected'), ('GUARDIAN_RELATIONSHIP_ENDED', 'Relationship ended')], max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guardian_relationship_events', to=settings.AUTH_USER_MODEL)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='guardians.guardianrelationship')),
            ],
            options={
                'ordering': ('created_at', 'uuid'),
            },
        ),
        migrations.CreateModel(
            name='MinorCreationRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('guardian_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='minor_creation_requests', to=settings.AUTH_USER_MODEL)),
                ('minor_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creation_request', to='patients.patientprofile')),
                ('relationship', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creation_request', to='guardians.guardianrelationship')),
            ],
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['verification_status', 'created_at'], name='guardian_verify_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['guardian_user', 'active'], name='guardian_user_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardianrelationship',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('guardian_user', 'minor_patient', 'relationship'), name='guardian_one_active_relationship_type'),
        ),
        migrations.AddConstraint(
            model_name='guardianrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('active', False), ('verification_status', 'VERIFIED'), _connector='OR'), name='guardian_active_requires_verified'),
        ),
        migrations.AddConstraint(
            model_name='minorcreationrequest',
            constraint=models.UniqueConstraint(fields=('guardian_user', 'idempotency_key'), name='guardian_minor_create_idempotency'),
        ),
    ]
