# Generated by Django 5.2.17 on 2026-08-25 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guardians", "0001_initial"),
        ("identities", "0004_identitydocument_unique_card_body_number"),
        ("patients", "0003_patientprofile_father_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="guardianrelationship",
            name="guardian_one_active_relationship_type",
        ),
        migrations.AddField(
            model_name="guardianrelationship",
            name="ended_reason_detail",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="guardianrelationship",
            name="evidence_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guardianrelationship",
            name="evidence_policy_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="guardianrelationship",
            name="guardian_identity_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardian_relationship_checks",
                to="identities.identitydocument",
            ),
        ),
        migrations.AddField(
            model_name="guardianrelationship",
            name="minor_identity_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="minor_relationship_checks",
                to="identities.identitydocument",
            ),
        ),
        migrations.AddField(
            model_name="guardianrelationship",
            name="name_evidence_result",
            field=models.CharField(
                choices=[
                    ("MATCH", "Match"),
                    ("MISMATCH", "Mismatch"),
                    ("UNAVAILABLE", "Unavailable"),
                ],
                default="UNAVAILABLE",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianrelationship",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("ended_at__isnull", True),
                    ("verification_status__in", ("PENDING", "VERIFIED")),
                ),
                fields=("guardian_user", "minor_patient", "relationship"),
                name="guardian_one_live_relationship_type",
            ),
        ),
    ]
