# Generated by Django 5.2.17 on 2026-08-08 21:24

import django.db.models.deletion
import documents.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, storage=documents.storage.PrivateMedicalStorage(), upload_to='')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=32)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('integrity_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('CORRUPTED', 'Corrupted'), ('QUARANTINED', 'Quarantined')], default='PENDING', max_length=16)),
                ('malware_scan_status', models.CharField(choices=[('NOT_CONFIGURED', 'Not configured'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Error')], default='NOT_CONFIGURED', max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_sha256', models.CharField(editable=False, max_length=64)),
                ('document_type', models.CharField(choices=[('LABORATORY', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('PRESCRIPTION', 'Prescription'), ('CONSULTATION', 'Consultation'), ('MEDICAL_REPORT', 'Medical report'), ('HOSPITAL_ADMISSION', 'Hospital admission'), ('DISCHARGE_SUMMARY', 'Discharge summary'), ('SURGERY_PROCEDURE', 'Surgery procedure'), ('PATHOLOGY', 'Pathology'), ('VACCINATION', 'Vaccination'), ('VITAL_SIGNS', 'Vital signs'), ('OTHER', 'Other')], max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('date_source', models.CharField(blank=True, choices=[('USER_ENTERED', 'User entered'), ('PDF_TEXT', 'PDF text'), ('OCR', 'OCR'), ('USER_CONFIRMED', 'User confirmed'), ('USER_CORRECTED', 'User corrected')], default='', max_length=24)),
                ('date_verified', models.BooleanField(default=False)),
                ('date_verified_at', models.DateTimeField(blank=True, null=True)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('physician_name', models.CharField(blank=True, max_length=255)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('TEXT_EXTRACTED', 'Text extracted'), ('DATE_DETECTED', 'Date detected'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=24)),
                ('archive_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_medical_documents', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_documents', to='patients.patientprofile')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_medical_documents', to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_document', to='documents.storedfile')),
            ],
            options={
                'ordering': ('-created_at', '-uuid'),
            },
        ),
        migrations.CreateModel(
            name='MedicalDocumentEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('MEDICAL_DOCUMENT_UPLOADED', 'Uploaded'), ('MEDICAL_DOCUMENT_METADATA_UPDATED', 'Metadata updated'), ('MEDICAL_DOCUMENT_DELETED', 'Deleted'), ('MEDICAL_DOCUMENT_DUPLICATE_REJECTED', 'Duplicate rejected'), ('MEDICAL_FILE_INTEGRITY_CHECKED', 'File integrity checked')], max_length=48)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_document_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='documents.medicaldocument')),
            ],
            options={
                'ordering': ('created_at', 'uuid'),
            },
        ),
        migrations.AddConstraint(
            model_name='medicaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('archive_status', 'ACTIVE')), fields=('patient', 'content_sha256'), name='documents_active_patient_content_unique'),
        ),
    ]
