# Generated by Django 5.2.17 on 2026-08-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='processing_failure_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('TEXT_EXTRACTED', 'Text extracted'), ('OCR_REQUIRED', 'OCR required'), ('DATE_DETECTED', 'Date detected'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=24),
        ),
        migrations.AlterField(
            model_name='medicaldocumentevent',
            name='event_type',
            field=models.CharField(choices=[('MEDICAL_DOCUMENT_UPLOADED', 'Uploaded'), ('MEDICAL_DOCUMENT_METADATA_UPDATED', 'Metadata updated'), ('MEDICAL_DOCUMENT_DELETED', 'Deleted'), ('MEDICAL_DOCUMENT_DUPLICATE_REJECTED', 'Duplicate rejected'), ('MEDICAL_FILE_INTEGRITY_CHECKED', 'File integrity checked'), ('PDF_EXTRACTION_QUEUED', 'PDF extraction queued'), ('PDF_EXTRACTION_STARTED', 'PDF extraction started'), ('PDF_TEXT_EXTRACTED', 'PDF text extracted'), ('PDF_OCR_REQUIRED', 'PDF OCR required'), ('PDF_EXTRACTION_FAILED', 'PDF extraction failed')], max_length=48),
        ),
    ]
