# Generated by Django 5.2.17 on 2026-08-09 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_medicaldocument_processing_status_and_more'),
        ('processing', '0004_remove_datecandidate_date_candidate_occurrence_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('TEXT_EXTRACTED', 'Text extracted'), ('OCR_REQUIRED', 'OCR required'), ('OCR_PROCESSING', 'OCR processing'), ('DATE_PROCESSING', 'Date processing'), ('DATE_DETECTED', 'Date detected'), ('DATE_NOT_FOUND', 'Date not found'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('DATE_CONFIRMED', 'Date confirmed'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=24),
        ),
        migrations.CreateModel(
            name='DocumentDateEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('DATE_CONFIRMED', 'Date confirmed'), ('DATE_CORRECTED', 'Date corrected'), ('DATE_RECONFIRMED', 'Date reconfirmed')], max_length=24)),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField()),
                ('source', models.CharField(choices=[('USER_ENTERED', 'User entered'), ('PDF_TEXT', 'PDF text'), ('OCR', 'OCR'), ('USER_CONFIRMED', 'User confirmed'), ('USER_CORRECTED', 'User corrected')], max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_document_date_events', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_events', to='processing.datecandidate')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='date_events', to='documents.medicaldocument')),
            ],
            options={
                'ordering': ('created_at', 'uuid'),
            },
        ),
    ]
