# Generated by Django 5.2.17 on 2026-08-09 13:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_classification_source(apps, schema_editor):
    MedicalDocument = apps.get_model("documents", "MedicalDocument")
    for document in MedicalDocument.objects.select_related("patient").iterator():
        source = (
            "USER_SELECTED"
            if document.patient.user_id == document.uploaded_by_id
            else "GUARDIAN_SELECTED"
        )
        MedicalDocument.objects.filter(pk=document.pk).update(
            classification_source=source
        )


def reset_classification_source(apps, schema_editor):
    MedicalDocument = apps.get_model("documents", "MedicalDocument")
    MedicalDocument.objects.update(classification_source="SYSTEM_DEFAULT")


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_medicaldocument_processing_status_and_more'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='classification_source',
            field=models.CharField(choices=[('USER_SELECTED', 'User selected'), ('GUARDIAN_SELECTED', 'Guardian selected'), ('SYSTEM_DEFAULT', 'System default')], default='SYSTEM_DEFAULT', max_length=24),
        ),
        migrations.RunPython(
            backfill_classification_source,
            reset_classification_source,
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='healthcare_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_documents', to='facilities.healthcarefacility'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentevent',
            name='event_type',
            field=models.CharField(choices=[('MEDICAL_DOCUMENT_UPLOADED', 'Uploaded'), ('MEDICAL_DOCUMENT_METADATA_UPDATED', 'Metadata updated'), ('DOCUMENT_TYPE_CHANGED', 'Document type changed'), ('DOCUMENT_FACILITY_CHANGED', 'Document facility changed'), ('DOCUMENT_LOCATION_UPDATED', 'Document location updated'), ('DOCUMENT_DEPARTMENT_UPDATED', 'Document department updated'), ('DOCUMENT_PHYSICIAN_METADATA_UPDATED', 'Document physician metadata updated'), ('MEDICAL_DOCUMENT_DELETED', 'Deleted'), ('MEDICAL_DOCUMENT_DUPLICATE_REJECTED', 'Duplicate rejected'), ('MEDICAL_FILE_INTEGRITY_CHECKED', 'File integrity checked'), ('PDF_EXTRACTION_QUEUED', 'PDF extraction queued'), ('PDF_EXTRACTION_STARTED', 'PDF extraction started'), ('PDF_TEXT_EXTRACTED', 'PDF text extracted'), ('PDF_OCR_REQUIRED', 'PDF OCR required'), ('PDF_EXTRACTION_FAILED', 'PDF extraction failed'), ('OCR_QUEUED', 'OCR queued'), ('OCR_STARTED', 'OCR started'), ('OCR_PAGE_COMPLETED', 'OCR page completed'), ('OCR_COMPLETED', 'OCR completed'), ('OCR_FAILED', 'OCR failed'), ('DATE_PROCESSING_QUEUED', 'Date processing queued'), ('DATE_PROCESSING_STARTED', 'Date processing started'), ('DATE_CANDIDATES_DETECTED', 'Date candidates detected'), ('DATE_NOT_FOUND', 'Date not found'), ('DATE_PROCESSING_FAILED', 'Date processing failed')], max_length=48),
        ),
    ]
