# Generated by Django 5.2.17 on 2026-08-09 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_medicaldocument_classification_source_and_more'),
        ('facilities', '0003_seed_iraqi_governorates'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['patient', 'archive_status', 'document_date'], name='archive_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['patient', 'archive_status', 'document_type'], name='archive_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['patient', 'archive_status', 'healthcare_facility'], name='archive_status_facility_idx'),
        ),
    ]
