# Generated by Django 5.2.17 on 2026-08-09 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_medicaldocument_archive_status_date_idx_and_more'),
        ('facilities', '0003_seed_iraqi_governorates'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['patient', 'archive_status', 'created_at'], name='archive_status_created_idx'),
        ),
    ]
