# Generated by Django 5.2.17 on 2026-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_medicaldocument_archive_status_created_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='integrity_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('CORRUPTED', 'Corrupted'), ('QUARANTINED', 'Quarantined'), ('MISSING', 'Missing')], default='PENDING', max_length=16),
        ),
    ]
