# Generated by Django 5.2.17 on 2026-08-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_storedfile_integrity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocumentevent',
            name='event_type',
            field=models.CharField(choices=[('MEDICAL_DOCUMENT_UPLOADED', 'Uploaded'), ('MEDICAL_DOCUMENT_METADATA_UPDATED', 'Metadata updated'), ('DOCUMENT_TYPE_CHANGED', 'Document type changed'), ('DOCUMENT_FACILITY_CHANGED', 'Document facility changed'), ('DOCUMENT_LOCATION_UPDATED', 'Document location updated'), ('DOCUMENT_DEPARTMENT_UPDATED', 'Document department updated'), ('DOCUMENT_PHYSICIAN_METADATA_UPDATED', 'Document physician metadata updated'), ('MEDICAL_DOCUMENT_DELETED', 'Deleted'), ('MEDICAL_DOCUMENT_DUPLICATE_REJECTED', 'Duplicate rejected'), ('MEDICAL_FILE_INTEGRITY_CHECKED', 'File integrity checked'), ('PDF_EXTRACTION_QUEUED', 'PDF extraction queued'), ('PDF_EXTRACTION_STARTED', 'PDF extraction started'), ('PDF_TEXT_EXTRACTED', 'PDF text extracted'), ('PDF_OCR_REQUIRED', 'PDF OCR required'), ('PDF_EXTRACTION_FAILED', 'PDF extraction failed'), ('OCR_QUEUED', 'OCR queued'), ('OCR_STARTED', 'OCR started'), ('OCR_PAGE_COMPLETED', 'OCR page completed'), ('OCR_COMPLETED', 'OCR completed'), ('OCR_FAILED', 'OCR failed'), ('DATE_PROCESSING_QUEUED', 'Date processing queued'), ('DATE_PROCESSING_STARTED', 'Date processing started'), ('DATE_CANDIDATES_DETECTED', 'Date candidates detected'), ('DATE_NOT_FOUND', 'Date not found'), ('DATE_PROCESSING_FAILED', 'Date processing failed'), ('LAB_EXTRACTION_QUEUED', 'Lab extraction queued'), ('LAB_EXTRACTION_STARTED', 'Lab extraction started'), ('LAB_EXTRACTION_COMPLETED', 'Lab extraction completed'), ('LAB_EXTRACTION_NOT_APPLICABLE', 'Lab extraction not applicable'), ('LAB_EXTRACTION_FAILED', 'Lab extraction failed')], max_length=48),
        ),
    ]
