# Generated by Django 5.2.17 on 2026-08-22 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_page_units(apps, schema_editor):
    """Create one MedicalDocumentPage per existing DocumentTextPage (page 1
    fallback for docs with no canonical text). FK re-pointing of existing
    DateCandidate/LabReportExtraction rows happens in 0013 AFTER the page_unit
    fields exist (their migrations depend on this one)."""
    MedicalDocument = apps.get_model("documents", "MedicalDocument")
    MedicalDocumentPage = apps.get_model("documents", "MedicalDocumentPage")
    DocumentTextPage = apps.get_model("processing", "DocumentTextPage")

    def page_status(doc_status, page):
        if doc_status == "FAILED":
            return "FAILED"
        if doc_status in {"AWAITING_CONFIRMATION", "DATE_CONFIRMED", "DATE_DETECTED", "DATE_NOT_FOUND", "INDEXED", "TEXT_EXTRACTED", "PARTIAL"}:
            if doc_status == "DATE_CONFIRMED":
                return "READY"
            if doc_status == "AWAITING_CONFIRMATION":
                return "AWAITING_CONFIRMATION"
            return "AWAITING_CONFIRMATION"
        if doc_status in {"PROCESSING", "OCR_PROCESSING", "DATE_PROCESSING"}:
            return "OCR_PROCESSING"
        return "QUEUED"

    created = 0
    for doc in MedicalDocument.objects.all().iterator():
        text_pages = DocumentTextPage.objects.filter(
            document_text__document_id=doc.uuid
        ).order_by("page_number")
        if text_pages.exists():
            for page in text_pages:
                MedicalDocumentPage.objects.update_or_create(
                    document_id=doc.uuid,
                    page_number=page.page_number,
                    defaults={
                        "processing_status": page_status(
                            doc.processing_status, page
                        ),
                    },
                )
                created += 1
        else:
            MedicalDocumentPage.objects.update_or_create(
                document_id=doc.uuid,
                page_number=1,
                defaults={"processing_status": page_status(doc.processing_status, None)},
            )
            created += 1


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_medicaldocument_content_fingerprint_and_more'),
        ('processing', '0006_documenttextspan'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocument',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('TEXT_EXTRACTED', 'Text extracted'), ('OCR_REQUIRED', 'OCR required'), ('OCR_PROCESSING', 'OCR processing'), ('DATE_PROCESSING', 'Date processing'), ('DATE_DETECTED', 'Date detected'), ('DATE_NOT_FOUND', 'Date not found'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('DATE_CONFIRMED', 'Date confirmed'), ('INDEXED', 'Indexed'), ('DUPLICATE_DETECTED', 'Duplicate detected'), ('PARTIAL', 'Partially processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=24),
        ),
        migrations.CreateModel(
            name='MedicalDocumentPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('processing_status', models.CharField(choices=[('QUEUED', 'Queued'), ('OCR_PROCESSING', 'OCR processing'), ('EXTRACTING', 'Extracting results'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='QUEUED', max_length=24)),
                ('report_subtype', models.CharField(choices=[('LAB_CHEMISTRY', 'Chemistry'), ('LAB_HORMONES', 'Hormones'), ('LAB_CBC', 'CBC'), ('RADIOLOGY', 'Radiology'), ('NARRATIVE', 'Narrative'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=24)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('date_verified', models.BooleanField(default=False)),
                ('date_source', models.CharField(blank=True, default='', max_length=24)),
                ('date_verified_at', models.DateTimeField(blank=True, null=True)),
                ('processing_failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.medicaldocument')),
            ],
            options={
                'ordering': ('page_number',),
                'indexes': [models.Index(fields=['document', 'page_number', 'processing_status'], name='documents_page_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'page_number'), name='documents_unique_document_page'), models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='documents_page_number_positive')],
            },
        ),
        migrations.RunPython(backfill_page_units, migrations.RunPython.noop),
    ]
