# Generated by Django 5.2.17 on 2026-08-14 11:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationIdentityExtractionJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability_digest', models.CharField(max_length=64)),
                ('document_type', models.CharField(choices=[('UNIFIED_NATIONAL_CARD', 'Unified National Card'), ('PASSPORT', 'Passport'), ('BIRTH_DOCUMENT', 'Birth document'), ('OTHER_GOVERNMENT_ID', 'Other government ID')], default='UNIFIED_NATIONAL_CARD', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FINALIZED', 'Finalized'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=16)),
                ('front_key', models.CharField(blank=True, default='', max_length=512)),
                ('back_key', models.CharField(blank=True, default='', max_length=512)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='reg_job_status_expiry_idx')],
            },
        ),
    ]
