# Generated by Django 5.2.17 on 2026-08-29 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability_digest', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('governorate', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('PENDING_EMAIL_VERIFICATION', 'Pending email verification'), ('EMAIL_VERIFIED', 'Email verified'), ('FINALIZED', 'Finalized'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_EMAIL_VERIFICATION', max_length=32)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='reg_session_status_expiry_idx')],
            },
        ),
        migrations.AddField(
            model_name='registrationidentityextractionjob',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_jobs', to='registration.registrationsession'),
        ),
    ]
