# Generated by Django 5.2.17 on 2026-08-09 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System')], default='USER', max_length=16)),
                ('resource_type', models.CharField(blank=True, default='', max_length=64)),
                ('resource_uuid', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(choices=[('ACCOUNT_CREATED', 'Account created'), ('ACCOUNT_STATUS_CHANGED', 'Account status changed'), ('ACCOUNT_ACTIVATED', 'Account activated'), ('ACCOUNT_CLAIM_SUBMITTED', 'Account claim submitted'), ('ACCOUNT_CLAIM_APPROVED', 'Account claim approved'), ('ACCOUNT_CLAIM_REJECTED', 'Account claim rejected'), ('PATIENT_ACCOUNT_LINKED', 'Patient account linked'), ('IDENTITY_DOCUMENT_UPLOADED', 'Identity document uploaded'), ('IDENTITY_DOCUMENT_VERIFIED', 'Identity document verified'), ('IDENTITY_DOCUMENT_REJECTED', 'Identity document rejected'), ('IDENTITY_DOCUMENT_REPLACED', 'Identity document replaced'), ('PATIENT_IDENTITY_STATUS_CHANGED', 'Patient identity status changed'), ('MINOR_CREATED', 'Minor created'), ('GUARDIAN_RELATIONSHIP_SUBMITTED', 'Guardian relationship submitted'), ('GUARDIAN_RELATIONSHIP_VERIFIED', 'Guardian relationship verified'), ('GUARDIAN_RELATIONSHIP_REJECTED', 'Guardian relationship rejected'), ('GUARDIAN_RELATIONSHIP_ENDED', 'Guardian relationship ended'), ('GUARDIAN_ACCESS_EXPIRED', 'Guardian access expired'), ('CLAIM_SUBMITTED', 'Claim submitted'), ('CLAIM_MORE_INFORMATION_REQUIRED', 'Claim more information required'), ('CLAIM_APPROVED', 'Claim approved'), ('CLAIM_REJECTED', 'Claim rejected'), ('ACCOUNT_ACTIVATION_CREATED', 'Account activation created'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_METADATA_UPDATED', 'Document metadata updated'), ('DOCUMENT_DELETED', 'Document deleted'), ('DOCUMENT_TYPE_CHANGED', 'Document type changed'), ('DOCUMENT_FACILITY_CHANGED', 'Document facility changed'), ('FILE_INTEGRITY_CHECKED', 'File integrity checked'), ('DATE_CONFIRMED', 'Date confirmed'), ('DATE_CORRECTED', 'Date corrected'), ('PDF_EXTRACTION_FAILED', 'PDF extraction failed'), ('OCR_FAILED', 'OCR failed'), ('INTEGRITY_FAILURE', 'Integrity failure')], max_length=64)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='patients.patientprofile')),
            ],
            options={
                'ordering': ('-created_at', '-uuid'),
                'indexes': [models.Index(fields=['patient', 'created_at'], name='audit_patient_created_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'), models.Index(fields=['resource_type', 'resource_uuid'], name='audit_resource_idx')],
            },
        ),
    ]
