# Generated by Django 5.2.17 on 2026-08-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ACCOUNT_CREATED', 'Account created'), ('ACCOUNT_STATUS_CHANGED', 'Account status changed'), ('ACCOUNT_ACTIVATED', 'Account activated'), ('ACCOUNT_CLAIM_SUBMITTED', 'Account claim submitted'), ('ACCOUNT_CLAIM_APPROVED', 'Account claim approved'), ('ACCOUNT_CLAIM_REJECTED', 'Account claim rejected'), ('PATIENT_ACCOUNT_LINKED', 'Patient account linked'), ('PATIENT_PROFILE_CREATED', 'Patient profile created'), ('IDENTITY_DOCUMENT_UPLOADED', 'Identity document uploaded'), ('IDENTITY_DOCUMENT_VERIFIED', 'Identity document verified'), ('IDENTITY_DOCUMENT_REJECTED', 'Identity document rejected'), ('IDENTITY_DOCUMENT_REPLACED', 'Identity document replaced'), ('PATIENT_IDENTITY_STATUS_CHANGED', 'Patient identity status changed'), ('MINOR_CREATED', 'Minor created'), ('GUARDIAN_RELATIONSHIP_SUBMITTED', 'Guardian relationship submitted'), ('GUARDIAN_RELATIONSHIP_VERIFIED', 'Guardian relationship verified'), ('GUARDIAN_RELATIONSHIP_REJECTED', 'Guardian relationship rejected'), ('GUARDIAN_RELATIONSHIP_ENDED', 'Guardian relationship ended'), ('GUARDIAN_RELATIONSHIP_DISMISSED', 'Guardian relationship dismissed'), ('GUARDIAN_ACCESS_EXPIRED', 'Guardian access expired'), ('CLAIM_SUBMITTED', 'Claim submitted'), ('CLAIM_MORE_INFORMATION_REQUIRED', 'Claim more information required'), ('CLAIM_APPROVED', 'Claim approved'), ('CLAIM_REJECTED', 'Claim rejected'), ('ACCOUNT_ACTIVATION_CREATED', 'Account activation created'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_METADATA_UPDATED', 'Document metadata updated'), ('DOCUMENT_DELETED', 'Document deleted'), ('DOCUMENT_TYPE_CHANGED', 'Document type changed'), ('DOCUMENT_FACILITY_CHANGED', 'Document facility changed'), ('FILE_INTEGRITY_CHECKED', 'File integrity checked'), ('DATE_CONFIRMED', 'Date confirmed'), ('DATE_CORRECTED', 'Date corrected'), ('PDF_EXTRACTION_FAILED', 'PDF extraction failed'), ('OCR_FAILED', 'OCR failed'), ('INTEGRITY_FAILURE', 'Integrity failure')], max_length=64),
        ),
    ]
