# Generated by Django 5.2.17 on 2026-08-08 18:08

import django.core.validators
import django.db.models.deletion
import patients.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digital_id', models.CharField(editable=False, max_length=17, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(validators=[patients.models.validate_not_future])),
                ('sex', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('UNSPECIFIED', 'Unspecified')], max_length=16)),
                ('nationality', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Use an uppercase ISO alpha-2 country code.', regex='^[A-Z]{2}$')])),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7)),
                ('identity_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING_VERIFICATION', 'Pending verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=24)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
