# Generated by Django 5.2.17 on 2026-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='governorate',
            field=models.CharField(blank=True, choices=[('AL_ANBAR', 'Al Anbar'), ('AL_QADISIYYAH', 'Al-Qadisiyyah'), ('BABIL', 'Babil'), ('BAGHDAD', 'Baghdad'), ('BASRA', 'Basra'), ('DHI_QAR', 'Dhi Qar'), ('DIYALA', 'Diyala'), ('DUHOK', 'Duhok'), ('ERBIL', 'Erbil'), ('HALABJA', 'Halabja'), ('KARBALA', 'Karbala'), ('KIRKUK', 'Kirkuk'), ('MAYSAN', 'Maysan'), ('MUTHANNA', 'Muthanna'), ('NAJAF', 'Najaf'), ('NINEVEH', 'Nineveh'), ('SALADIN', 'Saladin'), ('SULAYMANIYAH', 'Sulaymaniyah'), ('WASIT', 'Wasit')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='grandfather_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
