# Generated by Django 5.2.17 on 2026-08-18 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0010_alter_medicaldocumentevent_event_type'),
        ('processing', '0006_documenttextspan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportExtraction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('COMPLETED', 'Completed'), ('NOT_APPLICABLE', 'Not applicable'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_extractions', to='documents.medicaldocument')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('row_index', models.PositiveIntegerField()),
                ('test_name_raw', models.TextField(blank=True)),
                ('test_name_normalized', models.CharField(blank=True, default='', max_length=128)),
                ('result_raw', models.TextField(blank=True, default='')),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('result_text', models.TextField(blank=True, default='')),
                ('unit_raw', models.CharField(blank=True, default='', max_length=64)),
                ('unit_normalized', models.CharField(blank=True, default='', max_length=64)),
                ('reference_range_raw', models.TextField(blank=True, default='')),
                ('reference_low', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('reference_high', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('flag_raw', models.CharField(blank=True, default='', max_length=16)),
                ('extraction_confidence', models.FloatField()),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.labreportextraction')),
                ('source_spans', models.ManyToManyField(blank=True, related_name='lab_results', to='processing.documenttextspan')),
            ],
            options={
                'ordering': ('page_number', 'row_index'),
            },
        ),
        migrations.AddConstraint(
            model_name='labreportextraction',
            constraint=models.UniqueConstraint(fields=('document', 'pipeline_version'), name='labs_unique_document_pipeline_version'),
        ),
        migrations.AddConstraint(
            model_name='labreportextraction',
            constraint=models.CheckConstraint(condition=models.Q(('extraction_confidence__isnull', True), models.Q(('extraction_confidence__gte', 0.0), ('extraction_confidence__lte', 1.0)), _connector='OR'), name='labs_extraction_confidence_range'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['extraction', 'page_number', 'row_index'], name='labs_result_position_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['test_name_normalized'], name='labs_result_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.CheckConstraint(condition=models.Q(('page_number__gte', 1)), name='labs_result_page_positive'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.CheckConstraint(condition=models.Q(('row_index__gte', 0)), name='labs_result_row_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='labresult',
            constraint=models.CheckConstraint(condition=models.Q(('extraction_confidence__gte', 0.0), ('extraction_confidence__lte', 1.0)), name='labs_result_confidence_range'),
        ),
    ]
