# Generated by Django 5.2.17 on 2026-08-22 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_medicaldocument_processing_status_and_more'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreportextraction',
            name='page_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_extractions', to='documents.medicaldocumentpage'),
        ),
        migrations.AddConstraint(
            model_name='labreportextraction',
            constraint=models.UniqueConstraint(condition=models.Q(('page_unit__isnull', False)), fields=('page_unit', 'pipeline_version'), name='labs_unique_page_unit_pipeline_version'),
        ),
    ]
