# Generated by Django 5.2.17 on 2026-08-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_medicaldocument_processing_status_and_more'),
        ('labs', '0002_labreportextraction_page_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='labreportextraction',
            name='labs_unique_document_pipeline_version',
        ),
        migrations.AddConstraint(
            model_name='labreportextraction',
            constraint=models.UniqueConstraint(condition=models.Q(('page_unit__isnull', True)), fields=('document', 'pipeline_version'), name='labs_unique_document_pipeline_version'),
        ),
    ]
